version: '3'
services:

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "faxina"
      POSTGRES_PASSWORD: "faxina123"
      POSTGRES_DB: "faxina"

