version: '3'
services:

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "turismo"
      POSTGRES_PASSWORD: "turismo123"
      POSTGRES_DB: "turismo"
    volumes:
      - ./setup-server.sql:/docker-entrypoint-initdb.d/setup.sql
  redis:
    image: "redis"
    ports:
      - "6378:6379"
